<?php

/**
 * @file
 * Countries states.
 */

/**
 * Options list for the provinces of Canada.
 */
function webform_country_dropdown_CA() {
  return array(
    'BC' => t('British Columbia'),
    'ON' => t('Ontario'),
    'NL' => t('Newfoundland and Labrador'),
    'NS' => t('Nova Scotia'),
    'PE' => t('Prince Edward Island'),
    'NB' => t('New Brunswick'),
    'QC' => t('Quebec'),
    'MB' => t('Manitoba'),
    'SK' => t('Saskatchewan'),
    'AB' => t('Alberta'),
    'NT' => t('Northwest Territories'),
    'NU' => t('Nunavut'),
    'YT' => t('Yukon Territory'),
  );
}

/**
 * Options list for the provinces of Australia.
 */
function webform_country_dropdown_AU() {
  return array(
    'ACT' => 'Australian Capital Territory',
    'NSW' => 'New South Wales',
    'NT' => 'Northern Territory',
    'QLD' => 'Queensland',
    'TAS' => 'Tasmania',
    'SA' => 'South Australia',
    'VIC' => 'Victoria',
    'WA' => 'Western Australia',
  );
}

/**
 * Options list for the provinces of United Kingdom.
 */
function webform_country_dropdown_GB() {
  return array(
    'Aberdeenshire' => 'Aberdeenshire',
    'Angus/Forfarshire' => 'Angus/Forfarshire',
    'Argyllshire' => 'Argyllshire',
    'Ayrshire' => 'Ayrshire',
    'Banffshire' => 'Banffshire',
    'Bedfordshire' => 'Bedfordshire',
    'Berkshire' => 'Berkshire',
    'Berwickshire' => 'Berwickshire',
    'Blaenau Gwent' => 'Blaenau Gwent',
    'Bridgend' => 'Bridgend',
    'Buckinghamshire' => 'Buckinghamshire',
    'Buteshire' => 'Buteshire',
    'Caerphilly' => 'Caerphilly',
    'Caithness' => 'Caithness',
    'Cambridgeshire' => 'Cambridgeshire',
    'Cardiff' => 'Cardiff',
    'Carmarthenshire' => 'Carmarthenshire',
    'Ceredigion' => 'Ceredigion',
    'Cheshire' => 'Cheshire',
    'Clackmannanshire' => 'Clackmannanshire',
    'Conwy' => 'Conwy',
    'Cornwall' => 'Cornwall',
    'Cromartyshire' => 'Cromartyshire',
    'Cumberland' => 'Cumberland',
    'Denbighshire' => 'Denbighshire',
    'Derbyshire' => 'Derbyshire',
    'Devon' => 'Devon',
    'Dorset' => 'Dorset',
    'Dumfriesshire' => 'Dumfriesshire',
    'Dunbartonshire/Dumbartonshire' => 'Dunbartonshire/Dumbartonshire',
    'Durham' => 'Durham',
    'East Lothian/Haddingtonshire' => 'East Lothian/Haddingtonshire',
    'Essex' => 'Essex',
    'Fife' => 'Fife',
    'Flintshire' => 'Flintshire',
    'Gloucestershire' => 'Gloucestershire',
    'Gwynedd' => 'Gwynedd',
    'Greater London' => 'Greater London',
    'Hampshire' => 'Hampshire',
    'Herefordshire' => 'Herefordshire',
    'Hertfordshire' => 'Hertfordshire',
    'Huntingdonshire' => 'Huntingdonshire',
    'Inverness-shire' => 'Inverness-shire',
    'Isle of Anglesey' => 'Isle of Anglesey',
    'Kent' => 'Kent',
    'Kincardineshire' => 'Kincardineshire',
    'Kinross-shire' => 'Kinross-shire',
    'Kirkcudbrightshire' => 'Kirkcudbrightshire',
    'Lanarkshire' => 'Lanarkshire',
    'Lancashire' => 'Lancashire',
    'Leicestershire' => 'Leicestershire',
    'Lincolnshire' => 'Lincolnshire',
    'Merthyr Tydfil' => 'Merthyr Tydfil',
    'Middlesex' => 'Middlesex',
    'Midlothian/Edinburghshire' => 'Midlothian/Edinburghshire',
    'Monmouthshire' => 'Monmouthshire',
    'Morayshire' => 'Morayshire',
    'Nairnshire' => 'Nairnshire',
    'Neath Port Talbot' => 'Neath Port Talbot',
    'Newport' => 'Newport',
    'Norfolk' => 'Norfolk',
    'Northamptonshire' => 'Northamptonshire',
    'Northumberland' => 'Northumberland',
    'Nottinghamshire' => 'Nottinghamshire',
    'Orkney' => 'Orkney',
    'Oxfordshire' => 'Oxfordshire',
    'Peeblesshire' => 'Peeblesshire',
    'Pembrokeshire' => 'Pembrokeshire',
    'Perthshire' => 'Perthshire',
    'Powys' => 'Powys',
    'Renfrewshire' => 'Renfrewshire',
    'Rhondda Cynon Taff' => 'Rhondda Cynon Taff',
    'Ross-shire' => 'Ross-shire',
    'Roxburghshire' => 'Roxburghshire',
    'Rutland' => 'Rutland',
    'Selkirkshire' => 'Selkirkshire',
    'Shetland' => 'Shetland',
    'Shropshire' => 'Shropshire',
    'Somerset' => 'Somerset',
    'Staffordshire' => 'Staffordshire',
    'Stirlingshire' => 'Stirlingshire',
    'Suffolk' => 'Suffolk',
    'Surrey' => 'Surrey',
    'Sussex' => 'Sussex',
    'Sutherland' => 'Sutherland',
    'Swansea' => 'Swansea',
    'Torfaen' => 'Torfaen',
    'Tyne and Wear' => 'Tyne and Wear',
    'Vale of Glamorgan' => 'Vale of Glamorgan',
    'Warwickshire' => 'Warwickshire',
    'West Lothian/Linlithgowshire' => 'West Lothian/Linlithgowshire',
    'Westmorland' => 'Westmorland',
    'Wigtownshire' => 'Wigtownshire',
    'Wiltshire' => 'Wiltshire',
    'Worcestershire' => 'Worcestershire',
    'Wrexham' => 'Wrexham',
    'Yorkshire' => 'Yorkshire'
  );
}
